# ========================================
# Render.yaml - Deployment Configuration
# Amazon Review Intelligence Backend
# ========================================

services:
  # Backend API Service
  - type: web
    name: amazon-review-intelligence-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m nltk.downloader punkt stopwords vader_lexicon
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APIFY_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: ENABLE_AI
        value: true
      - key: ENABLE_EMOTIONS
        value: true
      - key: MAX_REVIEWS_PER_REQUEST
        value: 100
      - key: ALLOWED_ORIGINS
        value: https://amazon-review-intelligence.vercel.app/,http://localhost:3000
    healthCheckPath: /health
